### ISSUE TITLE
error: package not found

### ISSUE THREAD

**Issue by OpenWaygate** [bytecodealliance/go-modules#248]
Hi team, I am trying to follow this tutorial: https://component-model.bytecodealliance.org/language-support/go.html#:~:text=init%20example.com-,Next,-%2C%20we%20can%20generate

However I failed to generate the `internal` folder.

```shell
~/workspace/wasi-go
❯ tinygo version
tinygo version 0.34.0 darwin/arm64 (using go version go1.23.3 and LLVM version 18.1.2)
~/workspace/wasi-go
❯ wasm-tools -V
wasm-tools 1.220.0 (aab1ac81b 2024-11-12)

~/workspace/wasi-go
❯ tree .
.
├── add
│   ├── go.mod
│   └── go.sum
├── docs:adder@0.1.0.wasm
├── wit
│   └── add.wit
└── wkg.lock

3 directories, 5 files

~/workspace/wasi-go
❯ cd add 
~/workspace/wasi-go/add          
❯ go run go.bytecodealliance.org/cmd/wit-bindgen-go generate -o internal/ ../wit/add.wit 
error: package not found
     --> ../wit/add.wit:3:11
      |
    3 |   include wasi:cli/imports@0.2.0;
      |           ^-------
exit status 1
exit status 1
```

**Comment by ydnar** [comment]
You'll need a deps directory next to your WIT file with the other dependencies like wasi-cli. Then wasm-tools can find the missing dependencies.

**Comment by OpenWaygate** [comment]
Hi @ydnar, I have installed `cli` with `wit-deps`, but the problem remains.

<img width="1666" alt="image" src="https://github.com/user-attachments/assets/dee358c2-c235-4c4b-9eff-82c749a8a23d">

**Comment by ydnar** [comment]
cc @Mossaka

**Comment by Mossaka** [comment]
The problem is that in this WIT package, the imported `wasi:cli` is not present in the WIT package. You may want to use a tool called `wkg` to fetch the dependencies: 

```console
$ wkg -V       
wkg 0.7.4
$ wkg wit build       
WIT package written to docs:adder@0.1.0.wasm
```

And then you can do 
```console 
$ go run go.bytecodealliance.org/cmd/wit-bindgen-go generate -o internal/ ./docs:adder@0.1.0.wasm
```

**Comment by Mossaka** [comment]
This PR should make the documentation more clear: https://github.com/bytecodealliance/component-docs/issues/175
