### ISSUE TITLE
`generate` generates invalid go code 

### ISSUE THREAD

**Issue by MendyBerger** [bytecodealliance/go-modules#264]
`go.bytecodealliance.org/cmd/wit-bindgen-go generate` gives the following output:
```go
// IsQuery represents the imported method "is-query".
//
//	is-query: func(query: option<borrow<web-gl-query>>) -> g-lboolean
//
//go:nosplit
func (self WebGl2RenderingContext) IsQuery(query cm.Option[WebGlQuery]) (result GLboolean) {
	self0 := cm.Reinterpret[uint32](self)
	query0, query1 := lower_OptionBorrowWebGlQuery(query)
	result0 := wasmimport_WebGl2RenderingContextIsQuery((uint32)(self0), (uint32)(query0), (uint32)(query1))
	result = cm.U32ToBool((uint32)(result0))
	return
}
```
But this seems to be invalid go code. Generates the following error:
`cannot use cm.U32ToBool((uint32)(result0)) (value of type bool) as GLboolean value in assignment`

I think `result = cm.U32ToBool((uint32)(result0))` needs to be changed to `result = GLboolean(cm.U32ToBool((uint32)(result0)))`

**Comment by ydnar** [comment]
Can you supply a minimal WIT reproducer?

**Comment by ydnar** [comment]
Also, curious: why is WebGl2 in the type name instead of the WIT interface name (and Go package name)?

**Comment by MendyBerger** [comment]
Sorry, I should have included this in the original issue.

```wit
package webidl:browser;

world window {
  import global;
}

interface global {
  type g-lboolean = bool;
  resource web-gl-query {
  }
  resource web-gl2-rendering-context {
    is-query: func(query: option<borrow<web-gl-query>>) -> g-lboolean;
  }
}
```

(naming is auto generated as part of this project https://github.com/MendyBerger/browser.wit)

**Comment by ydnar** [comment]
Thanks! I’ll see if we can fix this using this WIT.

Couple thoughts:

- WIT names can have uppercase segments to indicate initialisms or acronyms, e.g. `web-GL`.
- Would it make sense to call the package `webidl:webgl`, or rename the `global`interface to `web-GL`?

**Comment by MendyBerger** [comment]
> Thanks! I’ll see if we can fix this using this WIT.

Thanks for the quick reply!

> WIT names can have uppercase segments to indicate initialisms or acronyms, e.g. web-GL.

Yeah, we should do that.

> Would it make sense to call the package webidl:webgl, or rename the globalinterface to web-GL?

`global` includes all web apis, not just webgl

**Comment by ydnar** [comment]
> `global` includes all web apis, not just webgl

Would it make sense to split up families of related APIs into their own interfaces, rather than group them all into one mega interface?

**Comment by MendyBerger** [comment]
> Would it make sense to split up families of related APIs into their own interfaces, rather than group them all into one mega interface?

Yes. But it's going to require figuring out where each families starts and ends, and I first wanna make it usable. And later we can think of how to break it up.
